apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tonystudent
  name: tonystudent-2
spec:
  containers:
  - image: nginx
    name: tonystudent
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
